name: gaia-live

services:
  # Replace placeholder service name
  gaia:
    build:
      context: .
      # docker-compose file is only used in dev
      target: dev
      dockerfile: Dockerfile
    # Replace placeholder service name
    image: gaia-live
    # Replace placeholder service name
    container_name: gaia-live
    ports:
      - '5000:8080'
