name: hermes-dev

services:
  hermes:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    image: hermes-dev
    container_name: hermes-dev
    # Prevent the container from exiting after initialisation
    command: /bin/sh -c "while sleep 1000; do :; done"

    volumes:
      # Replace placeholder service name
      - .:/workspaces/hermes:cached
